apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
  tolerations:
    - key: "prod"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"    
